### ISSUE TITLE
Markdown inside slots possible?

### ISSUE THREAD

**Issue by moso** [mdit-vue/vite-plugin-vue-markdown#10]
Hi,
I'm trying to make simple block wrappers, like tabs for code-blocks, etc. But whenever I wrap anything, it comes out as a string.

Maybe I'm tackling this too simple and need to render my slots in a very different way to include rendered Markdown, so this is more a question than a real issue.

Simplified example:

`/src/components/component.vue`:
```javascript
<template>
  <div class="component">
    <slot />
  </div>
</template>
```

`/pages/index.md`:

````vue
# Hello

<Component>
 ```css
.class {
    display: flex;
}
```
</Component>
````

The above will render the H1, but render the Vue component with the code block as a string:
```html
<h1>Hello</h1>

<div class="component">```css class{ display: flex; } ```</div>
```

Expected outcome:
```html
<h1>Hello</h1>

<div class="component">
  <pre>
    <code class="language-css">
      <!-- code here -->
    </code>
  </pre>
</div>
```

It would be nice if the Markdown would still render, but inside the slot. So far, no Google search comes up with anything concrete, other than Nuxt has been able to do this seamlessly.

Any pointers appreciated.

**Comment by moso** [comment]
Nevermind.

After looking through Vitebook's code, I realised it works out of the box with a new line between the tag and the content.

So for anyone else looking for this:

````html
<Component>

```css
.class {
  display: flex;
}
```

</Component>
````
... will work flawlessly.

**Comment by meteorlxy** [comment]
The reason is that, your code should be valid markdown syntax first. Beside vue components, you can try with standard html tags with / without empty lines.
