### ISSUE TITLE
Double code blocks?

### ISSUE THREAD

**Issue by Pigamo** [mdit-vue/vite-plugin-vue-markdown#20]
Looking at your about page for vitesse, there are 2 duplicate code blocks. Is this intentional?

I don't remember it being like this, so maybe it's a bug?

![image](https://user-images.githubusercontent.com/58117669/236647404-dda9846e-07df-4d8a-88e9-b6a5683f326a.png)

**Comment by antfu** [comment]
Upgrade both `markdown-it-shiki` and `vite-plugin-vue-markdown` should fix it.
