### ISSUE TITLE
Allow frontmatter to be exported or accessed when importing Markdown file

### ISSUE THREAD

**Issue by lobo-tuerto** [mdit-vue/vite-plugin-vue-markdown#4]
Hello!

Is there currently a way, or how difficult would it be to have access to the `frontmatter` in the parent component importing the Markdown file. Usually need this info there because I use the data for the UI that surrounds the MD and in other parts of the app.

I know I could probably use something to parse the **frontmatter** out of the file, but since you are already making it available inside the markdown content thought I'd ask. :)

Thanks!

**Comment by meteorlxy** [comment]
Check the example directory:

https://github.com/antfu/vite-plugin-vue-markdown/blob/72a2860c5842bcce63280045b68bdf48ff4c8a3e/example/App.vue#L11-L14
