### ISSUE TITLE
HMR stopped working in 0.21.1 

### ISSUE THREAD

**Issue by manniL** [mdit-vue/vite-plugin-vue-markdown#9]
Hey 👋🏻

Repo will be added soonish, but I wanted to let you know that HMR stopped working when using v0.21.1.
With v0.21.0, HMR still works fine.

---

# Reproduction

Not on StackBlitz because yarn resolutions / pnpm overrides do not work there 😢

1. Clone [this repo](https://github.com/manniL/vite-plugin-markdown-6)
2. `pnpm i`
3. `pnpm dev`
4. Try to change anything, e.g. the text or the WindiCSS class
5. See no HMR is happening

## "Fix"

1. Change the pnpm override to 0.21.0
2. `pnpm i`
3. `pnpm dev`
4. Try to change the WindiCSS class
5. See HMR working.

**Comment by antfu** [comment]
Yes, I am also aware of it, and that's why I locked Slidev to 0.21. Havn't yet investigated deep. PR welcome if anyone get some clue.

**Comment by manniL** [comment]
Resolved in latest version ☺️
